version: "3.8"
volumes:
  php-fpm-socket:
  db-store:
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./backend:/work/backend
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./backend:/work/backend
    ports:
      - 8001:80
    environment:
      PHP_HOST: app

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - ${DB_PORT:-33307}:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME:-xroom_db}
      - MYSQL_USER=${DB_USER:-user}
      - MYSQL_PASSWORD=${DB_PASS:-xroom}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-xroom}
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: library/redis:6.0.10-alpine